// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240319085856_addUsersToDb")]
    partial class addUsersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private beach, swimming pool, jacuzzi",
                            CreatedDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxury villa with stunning ocean views, private beach access, and modern amenities.",
                            ImageUrl = "https://example.com/ocean_villa.jpg",
                            Name = "Ocean Paradise Villa",
                            Occupancy = 8,
                            Rate = 300.0,
                            Sqft = 4000,
                            UpdatedDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Scenic views, hiking trails, fireplace",
                            CreatedDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Secluded villa nestled in the mountains, perfect for a peaceful getaway.",
                            ImageUrl = "https://example.com/mountain_villa.jpg",
                            Name = "Mountain Retreat Villa",
                            Occupancy = 6,
                            Rate = 250.0,
                            Sqft = 3500,
                            UpdatedDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Lake access, fishing pier, BBQ area",
                            CreatedDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Charming villa overlooking a serene lake, ideal for relaxation and water activities.",
                            ImageUrl = "https://example.com/lakeside_villa.jpg",
                            Name = "Lakeside Haven Villa",
                            Occupancy = 7,
                            Rate = 280.0,
                            Sqft = 3800,
                            UpdatedDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Infinity pool, spa, private dock",
                            CreatedDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Exquisite villa on the shores of a tranquil lake, offering unparalleled luxury and relaxation.",
                            ImageUrl = "https://example.com/luxury_lakeside_villa.jpg",
                            Name = "Luxury Lakeside Retreat",
                            Occupancy = 10,
                            Rate = 500.0,
                            Sqft = 6000,
                            UpdatedDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Garden, fireplace, outdoor dining area",
                            CreatedDate = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Quaint cottage nestled in the countryside, perfect for a romantic retreat.",
                            ImageUrl = "https://example.com/countryside_cottage.jpg",
                            Name = "Cozy Countryside Cottage",
                            Occupancy = 4,
                            Rate = 150.0,
                            Sqft = 2000,
                            UpdatedDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Pool with waterfall, sand dunes exploration, stargazing deck",
                            CreatedDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Spectacular villa oasis in the heart of the desert, offering luxury and adventure.",
                            ImageUrl = "https://example.com/desert_oasis_villa.jpg",
                            Name = "Desert Oasis Villa",
                            Occupancy = 8,
                            Rate = 400.0,
                            Sqft = 4500,
                            UpdatedDate = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Swimming pool with waterfall, outdoor bar, hammock garden",
                            CreatedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Exotic villa surrounded by lush tropical gardens, offering a true paradise experience.",
                            ImageUrl = "https://example.com/tropical_paradise_villa.jpg",
                            Name = "Tropical Paradise Villa",
                            Occupancy = 6,
                            Rate = 350.0,
                            Sqft = 5000,
                            UpdatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
